# Generated by Django 2.2.3 on 2019-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=50)),
                ('v_num', models.CharField(max_length=300)),
                ('V_type', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
