# Generated by Django 2.2.3 on 2019-07-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='First_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='password1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
