# Generated by Django 2.2.3 on 2019-07-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190730_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='First_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='password1',
            field=models.CharField(max_length=30),
        ),
    ]
