# Generated by Django 2.2.3 on 2019-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190730_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Mobileno',
            new_name='Mono',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='F_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='First_name',
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
