# Generated by Django 2.2.3 on 2019-07-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190731_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
