# Generated by Django 2.2.3 on 2019-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_driver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.AddField(
            model_name='driver',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='Mono',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='driver',
            name='licence',
            field=models.CharField(default='', max_length=20),
        ),
    ]
