# Generated by Django 2.2.3 on 2019-08-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190802_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.AddField(
            model_name='driver',
            name='City',
            field=models.CharField(choices=[('ahemdabad', 'ahemdabad'), ('baroda', 'baroda'), ('rajkot', 'rajkot'), ('junagadh', 'junagadh'), ('amreli', 'amreli')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='City',
            field=models.CharField(choices=[('ahemdabad', 'ahemdabad'), ('baroda', 'baroda'), ('rajkot', 'rajkot'), ('junagadh', 'junagadh'), ('amreli', 'amreli')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=60, unique=True),
        ),
    ]
