# Generated by Django 2.2.3 on 2019-08-08 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20190809_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 9, 5, 14, 5, 660239)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 9, 5, 14, 5, 660239)),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 9, 5, 14, 5, 660239)),
        ),
    ]
