# Generated by Django 2.2.3 on 2019-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_booking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
    ]
