# Generated by Django 2.2.3 on 2019-08-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20190810_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AlterField(
            model_name='booking',
            name='v_num',
            field=models.CharField(max_length=300),
        ),
    ]
