# Generated by Django 2.2.3 on 2019-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20190814_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='scat',
            name='c',
        ),
        migrations.AlterField(
            model_name='booking',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('two Wheelar', 'two Wheelar'), ('three Wheelar', 'three Wheelar'), ('four Wheelar', 'four Wheelar'), ('six Wheelar', 'six Wheelar')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subcategory',
            field=models.CharField(choices=[('bike', 'bike'), ('car', 'car'), ('tempo', 'tempo'), ('auto ricshaw', 'auto ricshaw'), ('truck', 'truck')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CAT',
        ),
        migrations.DeleteModel(
            name='SCAT',
        ),
    ]
