# Generated by Django 2.2.3 on 2019-08-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20190814_2220'),
        ('shop', '0045_auto_20190814_2229'),
    ]

    operations = [
    ]
