# Generated by Django 2.2.3 on 2019-08-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20190814_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='c',
        ),
    ]
