# Generated by Django 2.2.3 on 2019-08-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20190821_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
    ]
