# Generated by Django 2.2.3 on 2019-08-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_vehicle_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='email',
        ),
    ]
