# Generated by Django 2.2.3 on 2019-09-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_auto_20190823_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 7), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 7), null=True),
        ),
    ]
