# Generated by Django 2.2.3 on 2019-09-13 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_auto_20190908_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='id',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='id',
            new_name='vid',
        ),
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 13), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 13), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 13), null=True),
        ),
    ]
