# Generated by Django 2.2.3 on 2019-09-16 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_auto_20190916_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 16), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 16), null=True),
        ),
    ]
