# Generated by Django 2.2.3 on 2019-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_auto_20190917_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ex',
            field=models.IntegerField(default=1),
        ),
    ]
