# Generated by Django 2.2.3 on 2019-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_auto_20190918_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='adharcard',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='mediclereport',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='passbook',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='policeverification',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
