# Generated by Django 2.2.3 on 2019-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190727_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='V_type',
            field=models.CharField(max_length=30),
        ),
    ]
