# Generated by Django 2.2.3 on 2019-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190727_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='V_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
