# Generated by Django 2.2.3 on 2019-07-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190728_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_num',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
