# Generated by Django 2.2.3 on 2019-07-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190728_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=20)),
                ('Address', models.CharField(default='', max_length=500)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('City', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password1', models.CharField(max_length=30)),
            ],
        ),
    ]
