# Generated by Django 2.2.3 on 2019-08-08 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20190808_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 23, 20, 9, 54635)),
        ),
    ]
