# Generated by Django 2.2.3 on 2019-08-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20190809_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
