# Generated by Django 2.2.3 on 2019-08-14 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20190810_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SCAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CAT')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 14), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 14), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 14), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.CAT'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.SCAT'),
        ),
    ]
