# Generated by Django 2.2.3 on 2019-08-14 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20190814_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 14, 16, 38, 30, 137860, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 14, 16, 38, 30, 137860, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 14, 16, 38, 30, 137860, tzinfo=utc), null=True),
        ),
    ]
