# Generated by Django 2.2.3 on 2019-08-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_dcity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dcity',
        ),
    ]
