# Generated by Django 2.2.3 on 2019-08-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20190816_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='City',
            new_name='C',
        ),
    ]
