# Generated by Django 2.2.3 on 2019-08-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20190816_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='C',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dp',
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.C')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.C'),
        ),
        migrations.AddField(
            model_name='book',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.P'),
        ),
    ]
