# Generated by Django 2.2.3 on 2019-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20190822_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
