# Generated by Django 2.2.3 on 2019-08-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20190823_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='City',
            new_name='city',
        ),
    ]
