# Generated by Django 2.2.3 on 2019-09-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_auto_20190908_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='id',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='id',
            new_name='vid',
        ),
    ]
