# Generated by Django 2.2.3 on 2019-07-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='driver',
        ),
    ]
