# Generated by Django 2.2.3 on 2019-08-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20190808_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='o_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateTimeField(default=''),
        ),
    ]
