# Generated by Django 2.2.3 on 2019-08-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20190809_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
    ]
