# Generated by Django 2.2.3 on 2019-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_delete_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dcity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
