# Generated by Django 2.2.3 on 2019-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20190816_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pd',
            name='pid',
        ),
        migrations.AlterField(
            model_name='booking',
            name='City',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dp',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='pd',
        ),
    ]
