# Generated by Django 2.2.3 on 2019-08-16 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20190816_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=500)),
                ('Mono', models.CharField(default='', max_length=13)),
                ('C', models.CharField(max_length=13)),
                ('dp', models.CharField(max_length=13)),
                ('email', models.EmailField(default='', max_length=60)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('v_num', models.CharField(max_length=300)),
                ('startdate', models.DateField(blank=True, default=datetime.date(2019, 8, 16), null=True)),
                ('enddate', models.DateField(blank=True, default=datetime.date(2019, 8, 16), null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
