# Generated by Django 2.2.3 on 2019-08-20 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_auto_20190820_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 21), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 21), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 21), null=True),
        ),
    ]
