# Generated by Django 2.2.3 on 2019-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_auto_20190821_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
