# Generated by Django 2.2.3 on 2019-08-21 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20190821_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 22), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 22), null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 22), null=True),
        ),
    ]
