# Generated by Django 2.2.3 on 2019-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_auto_20190822_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('two Wheelar', 'two Wheelar'), ('three Wheelar', 'three Wheelar'), ('four Wheelar', 'four Wheelar'), ('six Wheelar', 'six Wheelar')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subcategory',
            field=models.CharField(choices=[('bike', 'bike'), ('car', 'car'), ('tempo', 'tempo'), ('auto ricshaw', 'auto ricshaw'), ('truck', 'truck')], default='', max_length=50),
        ),
    ]
