# Generated by Django 2.2.3 on 2019-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_vehicle_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
    ]
