# Generated by Django 2.2.3 on 2019-09-16 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_auto_20190916_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='enddate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 16, 22, 35, 14, 403982), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 16, 22, 35, 14, 403982), null=True),
        ),
    ]
