# Generated by Django 2.2.3 on 2019-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_auto_20190917_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
