# Generated by Django 2.2.3 on 2019-09-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_vehicle_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.FloatField(default=1.0),
        ),
    ]
