# Generated by Django 2.2.3 on 2019-09-18 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_book_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licence',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 18), null=True),
        ),
    ]
