# Generated by Django 2.2.3 on 2019-09-20 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0092_auto_20190920_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 21), null=True),
        ),
    ]
