# Generated by Django 2.0.5 on 2019-09-21 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_auto_20190921_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 22), null=True),
        ),
    ]
