# Generated by Django 2.0.5 on 2019-09-21 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_auto_20190922_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverbooking',
            fields=[
                ('db', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=500)),
                ('Mono', models.CharField(default='', max_length=13)),
                ('email', models.EmailField(default='', max_length=60)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('startdate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('enddate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('amount', models.IntegerField(default=1)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.C')),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.driver')),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.P')),
            ],
        ),
        migrations.RemoveField(
            model_name='dbook',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dbook',
            name='did',
        ),
        migrations.RemoveField(
            model_name='dbook',
            name='p',
        ),
        migrations.DeleteModel(
            name='dbook',
        ),
    ]
