# Generated by Django 2.0.5 on 2019-09-26 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_auto_20190922_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 27), null=True),
        ),
        migrations.AlterField(
            model_name='scat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
