# Generated by Django 2.0.5 on 2019-09-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0096_auto_20190927_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cat')),
            ],
        ),
        migrations.RemoveField(
            model_name='scat',
            name='sc',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory'),
        ),
        migrations.DeleteModel(
            name='scat',
        ),
    ]
