# Generated by Django 2.0.5 on 2019-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_auto_20190927_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
