# Generated by Django 2.0.5 on 2019-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0098_driver_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='lastname',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
