# Generated by Django 2.0.5 on 2019-09-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0100_auto_20190928_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbooking',
            name='did',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.driver'),
        ),
    ]
