# Generated by Django 2.0.5 on 2019-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0101_auto_20190928_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbooking',
            name='did',
            field=models.IntegerField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
