# Generated by Django 2.0.5 on 2019-09-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_auto_20190928_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=500)),
                ('Mono', models.CharField(default='', max_length=13)),
                ('city', models.CharField(default='', max_length=20)),
                ('Pincode', models.CharField(default='', max_length=6)),
                ('adharcard', models.FileField(default='', upload_to='documents/')),
                ('password', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Mono',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='o_name',
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='did',
            field=models.IntegerField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 29), null=True),
        ),
    ]
