# Generated by Django 2.0.5 on 2019-09-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0103_auto_20190929_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
