# Generated by Django 2.0.5 on 2019-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0105_auto_20190929_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='o_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
