# Generated by Django 2.0.5 on 2019-09-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_vehicle_o_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='o_name',
        ),
    ]
