# Generated by Django 2.0.5 on 2019-09-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_remove_vehicle_o_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory'),
        ),
    ]
