# Generated by Django 2.0.5 on 2019-09-30 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_auto_20190929_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbooking',
            name='did',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 30), null=True),
        ),
    ]
