# Generated by Django 2.0.5 on 2019-10-01 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0109_auto_20190930_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverbooking',
            name='did',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rdate',
            field=models.DateField(blank=True, default=datetime.date(2019, 10, 2), null=True),
        ),
    ]
